### ISSUE TITLE
mihome-lamp related errors in the log

### ISSUE THREAD

**Issue by AlexVVVx** [MeisterTR/ioBroker.mihome-lamp#16]
I am using Xiaomi-Philips EyeCare lamp with mihome-lamp adapter and it wors as expected. but looking into the log I see errors below. It happens a couple of times a day and does not connected somehow to the lamp activivties. The lamp was off at 6am. If you need any further details please let me know.

host.iobroker	2018-04-04 06:03:50.979	info	instance system.adapter.mihome-lamp.0 started with pid 8362

host.iobroker	2018-04-04 06:03:20.962	info	Restart adapter system.adapter.mihome-lamp.0 because enabled

host.iobroker	2018-04-04 06:03:20.962	error	instance system.adapter.mihome-lamp.0 terminated with code 0 (OK)

Caught	2018-04-04 06:03:20.962	error	by controller[0]: at UDP.onMessage (dgram.js:561:8)

Caught	2018-04-04 06:03:20.962	error	by controller[0]: at Socket.emit (events.js:191:7)

Caught	2018-04-04 06:03:20.962	error	by controller[0]: at emitTwo (events.js:106:13)

Caught	2018-04-04 06:03:20.961	error	by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.mihome-lamp/main.js:254:17)

Caught	2018-04-04 06:03:20.961	error	by controller[0]: at getStates (/opt/iobroker/node_modules/iobroker.mihome-lamp/main.js:163:42)

Caught	2018-04-04 06:03:20.960	error	by controller[0]: TypeError: Cannot read property 'length' of undefined

mihome-lamp.0	2018-04-04 06:03:20.936	info	terminating

mihome-lamp.0	2018-04-04 06:03:20.924	error	at UDP.onMessage (dgram.js:561:8)

mihome-lamp.0	2018-04-04 06:03:20.924	error	at Socket.emit (events.js:191:7)

mihome-lamp.0	2018-04-04 06:03:20.924	error	at emitTwo (events.js:106:13)

mihome-lamp.0	2018-04-04 06:03:20.924	error	at Socket. (/opt/iobroker/node_modules/iobroker.mihome-lamp/main.js:254:17)

mihome-lamp.0	2018-04-04 06:03:20.924	error	at getStates (/opt/iobroker/node_modules/iobroker.mihome-lamp/main.js:163:42)

mihome-lamp.0	2018-04-04 06:03:20.924	error	TypeError: Cannot read property 'length' of undefined

mihome-lamp.0	2018-04-04 06:03:20.921	error	uncaught exception: Cannot read property 'length' of undefined

**Comment by MeisterTR** [comment]
i know about that and fix it in the next version
